### ISSUE TITLE
What is the roadmap?

### ISSUE THREAD

**Issue by leobauza** [vigetlabs/microcosm#258]
We need some kind of roadmap document to guide contribution.

- [ ] What is the roadmap? (add to project README)
- [ ] ~Add roadmap reference to site~
- [ ] Add roadmap reference to CONTRIBUTING.md

**Comment by nhunzaker** [comment]
I laid out some thoughts here:
https://github.com/vigetlabs/microcosm/issues/281
