### ISSUE TITLE
The road to Flow

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/microcosm#304]
Internally, we're really digging [Flow](http://flowtype.org). It would be great to move Microcosm over to it.

## Goals

- [x] Move all constructor functions to classes (#305)
- [x] Verify there isn't a performance regression moving to transpiled ES6 classes (#306)
- [x] Investigate API documentation generation with [documentation.js](https://github.com/documentationjs/documentation) (#307)
- [ ] Translate every single file...

## Bonus points

- [ ] Investigate generating and verifying correctness of TypeScript definitions

**Comment by nhunzaker** [comment]
@leobauza I think a good first class to work on would be the CompareTree:
https://github.com/vigetlabs/microcosm/blob/master/src/compare-tree/index.js

This class is pretty isolated. It seems like a prime candidate.

**Comment by nhunzaker** [comment]
Let's put this on hold until we wrap up the new documentation stuff.

**Comment by nhunzaker** [comment]
We did it!
